gwp_asan: Fix build error for Android i386 CRTS
Fix for build error below:

-- Build files have been written to: /media/otherhd/clang/out/lib/clangrt-i386-host
INFO:__main__:check_call:21:46:42 /media/otherhd/clang/prebuilts/cmake/linux-x86/bin/ninja
[485/578] Building CXX object lib/gwp_asan/CMakeFiles/RTGwpAsanSegvHandler.i386.dir/optional/segv_handler_posix.cpp.o
FAILED: /media/otherhd/clang/out/stage2-install/bin/clang++  --sysroot=/media/otherhd/clang/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot   -I/media/otherhd/clang/toolchain/llvm-project/compiler-rt/lib/gwp_asan/.. -fdebug-prefix-map=/media/otherhd/clang= --gcc-toolchain=/media/otherhd/clang/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8 -B/media/otherhd/clang/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/bin --target=i386-linux-gnu -march=i686 -Wall -Werror -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG    -m32 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fno-rtti -fno-exceptions -nostdinc++ -pthread -fPIC -fno-omit-frame-pointer -MD -MT lib/gwp_asan/CMakeFiles/RTGwpAsanSegvHandler.i386.dir/optional/segv_handler_posix.cpp.o -MF lib/gwp_asan/CMakeFiles/RTGwpAsanSegvHandler.i386.dir/optional/segv_handler_posix.cpp.o.d -o lib/gwp_asan/CMakeFiles/RTGwpAsanSegvHandler.i386.dir/optional/segv_handler_posix.cpp.o -c /media/otherhd/clang/toolchain/llvm-project/compiler-rt/lib/gwp_asan/optional/segv_handler_posix.cpp
/media/otherhd/clang/toolchain/llvm-project/compiler-rt/lib/gwp_asan/optional/segv_handler_posix.cpp:114:50: error: expected ')'
    snprintf(ThreadBuffer, kThreadBufferLen, "%" PRIu64, ThreadID);
                                                 ^
/media/otherhd/clang/toolchain/llvm-project/compiler-rt/lib/gwp_asan/optional/segv_handler_posix.cpp:114:13: note: to match this '('
    snprintf(ThreadBuffer, kThreadBufferLen, "%" PRIu64, ThreadID);
            ^
1 error generated.

Change-Id: Ic5be0c5690e45889512e591f2e0769873a929880
Signed-off-by: mydongistiny <jaysonedson@gmail.com>